DATA = {
    "ALGORITHM" : "A step-by-step procedure or formula for solving a problem.",
    "BIT (BINARY DIGIT)" : "The smallest unit of data in a computer, representing 0 or 1.",
    "BYTE" : "A gtoup of 8 bits, used to store a single character.",
    "CACHE MEMORY" : "A small-sized type of volatile computer memory that provides high-speed data access to the processor.",
    "CENTRAL PROCESSING UNIT (CPU)" : "The main processor of a computer that executes instructions.",
    "CLOCK SPEED" : "The speed at which a CPU processes instructions, measured in GHz.",
    "COMPILER" : "A program that translates source code written in a high-level language into machine code.",
    "DATA BUS" : "A communication system that transfers data between components inside a computer.",
    "DIGITAL SIGNAL PROCESSING (DSP)" : "The manipulation of digits signals to improve signal quality or extract information.",
    "EMBEDDED SYSTEM" : "A specialized computing system that performs dedicated functions within a larger system.",
    "FIRMWARE" : "A permanent software programmed into a read-only memory (ROM) of a device.",
    "FLOATING POINT UNIT (FPU)" : "A part of a CPU dedicated to handling floating-point calculations.",
    "GRAPHICS PROCESSING UNIT (GPU)" : "A specialized processor designed for rendering images and video.",
    "INTEGRATED CIRCUIT (IC)" : "A set of electronic circuits embedded in a single semiconductor chip.",
    "INTERRUPT" : "A signal sent to the processor to request immediate attantion for a task.",
    "KERNEL" : "The core of an operating system that manages system resources and hardware.",
    "LOGIC GATES" : "Basic building blocks of digital circuits that perform logical operations like AND, OR, and NOT.",
    "MACHINE CODE" : "A low-level programming language that is directly executed by a computer's CPU.",
    "MICROCONTROLLER" : "A small computer on a single integrated circuit that includes a processor, memory, and Input or Ouput peripherals.",
    "MULTIPROCESSING" : "The use of multiple processors to perform computing tasks simultaneously.",
    "NETWORK PROTOCOL" : "A set of rules defining how data is transmitted over a network.",
    "OPERATING SYSTEM (OS)" : "A System Software that manages computer hardware and software resources.",
    "PARALLEL COMPUTING" : "The simultaneous execution of multiple tasks or processes.",
    "PERIPHERAL DEVICES" : "An external device connected to a computer, such as keyboard or printer.",
    "PIPELINE PROCESSING" : "A technique where multiple instructions are overlapped in execution to improve efficiency.",
    "RANDOM ACCESS MEMORY (RAM)" : "Volatile memory used to store data and instructions temporarily.",
    "REGISTER" : "A small, fast storage location in a CPU used to hold temporary data and instructions.",
    "READ-ONLY MEMORY (ROM)" : "A non-volatile memory that retains its data even when powered off.",
    "SYSTEM-ON-CHIP (SoC)" : "An integrated circuit that incorporates all components of a computer system.",
    "VIRTUAL MEMORY" : "A memory management technique that extends RAM using disk storage."
    }
a = input ("Say: ")
print(DATA[a])
